---
$schema: "http://json-schema.org/draft-07/schema#"
title: Config
description: "Settings for `config.yaml`"
type: object
properties:
  playback:
    default:
      image_duration: 10
      muted: false
      pause_on_unfocus: false
      synchronized: false
      volume: 1.0
    allOf:
      - $ref: "#/definitions/Playback"
  release:
    default:
      check: true
    allOf:
      - $ref: "#/definitions/Release"
  view:
    default:
      confirm_discard_playlist: true
      language: en-US
      theme: dark
    allOf:
      - $ref: "#/definitions/View"
definitions:
  Language:
    description: Display language.
    oneOf:
      - description: English
        type: string
        enum:
          - en-US
      - description: French
        type: string
        enum:
          - fr-FR
      - description: German
        type: string
        enum:
          - de-DE
      - description: Polish
        type: string
        enum:
          - pl-PL
      - description: Brazilian Portuguese
        type: string
        enum:
          - pt-BR
  Playback:
    type: object
    properties:
      image_duration:
        description: "How long to show images, in seconds."
        default: 10
        type: integer
        format: uint
        minimum: 1.0
      muted:
        description: Whether all players are muted.
        default: false
        type: boolean
      pause_on_unfocus:
        description: Whether to pause when window loses focus.
        default: false
        type: boolean
      synchronized:
        description: Whether to synchronize play/pause/seek events in media of the same category.
        default: false
        type: boolean
      volume:
        description: "Volume level when not muted. 1.0 is 100%, 0.01 is 1%."
        default: 1.0
        type: number
        format: float
  Release:
    type: object
    properties:
      check:
        description: "Whether to check for new releases. If enabled, the application will check at most once every 24 hours."
        default: true
        type: boolean
  Theme:
    description: Visual theme.
    type: string
    enum:
      - light
      - dark
  View:
    type: object
    properties:
      confirm_discard_playlist:
        default: true
        type: boolean
      language:
        default: en-US
        allOf:
          - $ref: "#/definitions/Language"
      theme:
        default: dark
        allOf:
          - $ref: "#/definitions/Theme"
