---
$schema: "http://json-schema.org/draft-07/schema#"
title: Config
description: "Settings for `config.yaml`"
type: object
properties:
  language:
    default: en-US
    allOf:
      - $ref: "#/definitions/Language"
  playback:
    default:
      max: 4
      muted: false
    allOf:
      - $ref: "#/definitions/Playback"
  release:
    default:
      check: true
    allOf:
      - $ref: "#/definitions/Release"
  theme:
    default: Dark
    allOf:
      - $ref: "#/definitions/Theme"
definitions:
  Language:
    description: Display language.
    oneOf:
      - description: English
        type: string
        enum:
          - en-US
  Playback:
    type: object
    properties:
      max:
        default: 4
        type: integer
        format: uint
        minimum: 0.0
      muted:
        default: false
        type: boolean
  Release:
    type: object
    properties:
      check:
        description: "Whether to check for new releases. If enabled, the application will check at most once every 24 hours."
        default: true
        type: boolean
  Theme:
    description: Visual theme.
    type: string
    enum:
      - Light
      - Dark
